import type { ImageKey } from "@/lib/images";

export type GalleryProject = {
  id: string;
  title: string;
  category:
    | "Villa Decoration"
    | "Home Decoration"
    | "Office Decoration"
    | "Corporate & Hospitality"
    | "Lighting & Outdoor"
    | "Signature Styling";
  year: string;
  ratio: "portrait" | "landscape" | "tall";
  image: ImageKey;
  placeholder: boolean;
};

/**
 * Curated Gallery of 41 Real Festive Occasions Projects in Dubai & UAE.
 * 100% authentic client-supplied installation photography. 
 */
export const galleryProjects: GalleryProject[] = [
  {
    id: "g01",
    title: "Commercial Entrance Candy Cane & Garland Pillar",
    category: "Corporate & Hospitality",
    year: "Recent Work",
    ratio: "portrait",
    image: "client01",
    placeholder: false,
  },
  {
    id: "g02",
    title: "Velvet Crimson Ribbons & Gold Christmas Tree",
    category: "Villa Decoration",
    year: "Recent Work",
    ratio: "portrait",
    image: "client02",
    placeholder: false,
  },
  {
    id: "g03",
    title: "Cascading Burgundy Baubles & Floating Taper Candles",
    category: "Villa Decoration",
    year: "Recent Work",
    ratio: "portrait",
    image: "client03",
    placeholder: false,
  },
  {
    id: "g04",
    title: "Festive Dining Table Runner & Candle Styling",
    category: "Signature Styling",
    year: "Recent Work",
    ratio: "portrait",
    image: "client04",
    placeholder: false,
  },
  {
    id: "g05",
    title: "Grand Villa Living Room & Mantle Garland",
    category: "Villa Decoration",
    year: "Recent Work",
    ratio: "landscape",
    image: "client05",
    placeholder: false,
  },
  {
    id: "g06",
    title: "Grand Champagne Tree Styling & Luxury Gift Boxes",
    category: "Home Decoration",
    year: "Recent Work",
    ratio: "portrait",
    image: "client06",
    placeholder: false,
  },
  {
    id: "g07",
    title: "Villa Dining & Holiday Ambiance",
    category: "Villa Decoration",
    year: "Recent Work",
    ratio: "portrait",
    image: "client07",
    placeholder: false,
  },
  {
    id: "g08",
    title: "Festive Tree Lighting & Baubles",
    category: "Lighting & Outdoor",
    year: "Recent Work",
    ratio: "portrait",
    image: "client08",
    placeholder: false,
  },
  {
    id: "g09",
    title: "Holiday Reception & Accent Styling",
    category: "Office Decoration",
    year: "Recent Work",
    ratio: "portrait",
    image: "client09",
    placeholder: false,
  },
  {
    id: "g10",
    title: "Grand Commercial Atrium Tree Installation",
    category: "Corporate & Hospitality",
    year: "Recent Work",
    ratio: "portrait",
    image: "client10",
    placeholder: false,
  },
  {
    id: "g11",
    title: "Private Residence — Tree & Ornaments",
    category: "Home Decoration",
    year: "Recent Work",
    ratio: "portrait",
    image: "client11",
    placeholder: false,
  },
  {
    id: "g12",
    title: "Luxury Villa Living Room Scheme",
    category: "Villa Decoration",
    year: "Recent Work",
    ratio: "portrait",
    image: "client12",
    placeholder: false,
  },
  {
    id: "g13",
    title: "Organic Pine & Red Berry Villa Entrance Arch",
    category: "Lighting & Outdoor",
    year: "Recent Work",
    ratio: "portrait",
    image: "client13",
    placeholder: false,
  },
  {
    id: "g14",
    title: "Snow-Flocked Champagne Winter Wonderland Tree",
    category: "Home Decoration",
    year: "Recent Work",
    ratio: "portrait",
    image: "client14",
    placeholder: false,
  },
  {
    id: "g15",
    title: "Illuminated Palm Trees & Grand Villa Doorway Arch",
    category: "Lighting & Outdoor",
    year: "Recent Work",
    ratio: "portrait",
    image: "client15",
    placeholder: false,
  },
  {
    id: "g16",
    title: "Handcrafted Holiday Tree Ornaments",
    category: "Signature Styling",
    year: "Recent Work",
    ratio: "portrait",
    image: "client16",
    placeholder: false,
  },
  {
    id: "g17",
    title: "Grand Hallway Christmas Tree",
    category: "Villa Decoration",
    year: "Recent Work",
    ratio: "portrait",
    image: "client17",
    placeholder: false,
  },
  {
    id: "g18",
    title: "Hospitality Lounge Festive Setting",
    category: "Corporate & Hospitality",
    year: "Recent Work",
    ratio: "portrait",
    image: "client18",
    placeholder: false,
  },
  {
    id: "g19",
    title: "Luxury Apartment Festive Glow",
    category: "Home Decoration",
    year: "Recent Work",
    ratio: "portrait",
    image: "client19",
    placeholder: false,
  },
  {
    id: "g20",
    title: "Bespoke Residence Holiday Theme",
    category: "Home Decoration",
    year: "Recent Work",
    ratio: "portrait",
    image: "client20",
    placeholder: false,
  },
  {
    id: "g21",
    title: "Villa Staircase & Foyer Decoration",
    category: "Villa Decoration",
    year: "Recent Work",
    ratio: "portrait",
    image: "client21",
    placeholder: false,
  },
  {
    id: "g22",
    title: "Custom Red Bauble Tree Scheme",
    category: "Signature Styling",
    year: "Recent Work",
    ratio: "portrait",
    image: "client22",
    placeholder: false,
  },
  {
    id: "g23",
    title: "Snow-Flocked Tree with Polar Bears",
    category: "Signature Styling",
    year: "Recent Work",
    ratio: "portrait",
    image: "client23",
    placeholder: false,
  },
  {
    id: "g24",
    title: "Palm Jumeirah Villa — Festive Setup",
    category: "Villa Decoration",
    year: "Recent Work",
    ratio: "portrait",
    image: "client24",
    placeholder: false,
  },
  {
    id: "g25",
    title: "Emirates Hills Residence Decor",
    category: "Villa Decoration",
    year: "Recent Work",
    ratio: "portrait",
    image: "client25",
    placeholder: false,
  },
  {
    id: "g26",
    title: "Modern Minimalist Christmas Tree",
    category: "Home Decoration",
    year: "Recent Work",
    ratio: "portrait",
    image: "client26",
    placeholder: false,
  },
  {
    id: "g27",
    title: "Commercial Illuminated Wreath Archway",
    category: "Corporate & Hospitality",
    year: "Recent Work",
    ratio: "portrait",
    image: "client27",
    placeholder: false,
  },
  {
    id: "g28",
    title: "Retail Boutique Holiday Display",
    category: "Corporate & Hospitality",
    year: "Recent Work",
    ratio: "portrait",
    image: "client28",
    placeholder: false,
  },
  {
    id: "g29",
    title: "Festive Dining Table Centerpiece",
    category: "Signature Styling",
    year: "Recent Work",
    ratio: "portrait",
    image: "client29",
    placeholder: false,
  },
  {
    id: "g30",
    title: "Grand Entrance Archway with Crimson Bows",
    category: "Lighting & Outdoor",
    year: "Recent Work",
    ratio: "portrait",
    image: "client30",
    placeholder: false,
  },
  {
    id: "g31",
    title: "Bespoke Doorway Garland & Baubles",
    category: "Lighting & Outdoor",
    year: "Recent Work",
    ratio: "portrait",
    image: "client31",
    placeholder: false,
  },
  {
    id: "g32",
    title: "Luxury Tree Installation in Villa Salon",
    category: "Villa Decoration",
    year: "Recent Work",
    ratio: "portrait",
    image: "client32",
    placeholder: false,
  },
  {
    id: "g33",
    title: "Traditional Red & Gold Tree Styling",
    category: "Signature Styling",
    year: "Recent Work",
    ratio: "portrait",
    image: "client33",
    placeholder: false,
  },
  {
    id: "g34",
    title: "Whimsical Candy Cane & Peppermint Tree",
    category: "Signature Styling",
    year: "Recent Work",
    ratio: "portrait",
    image: "client34",
    placeholder: false,
  },
  {
    id: "g35",
    title: "Cascading Red Ornaments Tree Showstopper",
    category: "Signature Styling",
    year: "Recent Work",
    ratio: "portrait",
    image: "client35",
    placeholder: false,
  },
  {
    id: "g36",
    title: "Illuminated Garden & Facade Tree",
    category: "Lighting & Outdoor",
    year: "Recent Work",
    ratio: "portrait",
    image: "client36",
    placeholder: false,
  },
  {
    id: "g37",
    title: "Warm White Fairy Light Canopy",
    category: "Lighting & Outdoor",
    year: "Recent Work",
    ratio: "portrait",
    image: "client37",
    placeholder: false,
  },
  {
    id: "g38",
    title: "Rose Gold & Champagne Starlight Tree",
    category: "Signature Styling",
    year: "Recent Work",
    ratio: "portrait",
    image: "client38",
    placeholder: false,
  },
  {
    id: "g39",
    title: "Executive Penthouse Holiday Lounge",
    category: "Home Decoration",
    year: "Recent Work",
    ratio: "portrait",
    image: "client39",
    placeholder: false,
  },
  {
    id: "g40",
    title: "Candlelit Tree & Festive Portal Framing",
    category: "Lighting & Outdoor",
    year: "Recent Work",
    ratio: "portrait",
    image: "client40",
    placeholder: false,
  },
  {
    id: "g41",
    title: "Bespoke Evening Festive Illumination",
    category: "Lighting & Outdoor",
    year: "Recent Work",
    ratio: "portrait",
    image: "client41",
    placeholder: false,
  },
];